[account]
id = "juglans-wallet"
name = "Juglans Wallet"

[ai]
default_model = "deepseek-chat"

[ai.providers.deepseek]
api_key = "sk-897fdc3c264d463da77a35b2d5c3e280"

[server]
host = "127.0.0.1"
port = 8090
